#server:
#  port: 8761
#eureka:
#  instance:
#    hostname: localhost
#  client:
#    #自己就是注册中心，不用注册自己
#    registerWithEureka: false
#    #要不要去注册中心获取其他服务的地址
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

server:
  port: 8761

eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://peer2:8769/eureka/
spring:
  config:
    activate:
      on-profile: peer1